-- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL read committed;
-- SHOW default_transaction_isolation;


-- ALTER DATABASE isolation_exp SET DEFAULT_TRANSACTION_ISOLATION TO 'SERIALIZABLE';
-- ALTER DATABASE isolation_exp SET DEFAULT_TRANSACTION_ISOLATION TO 'REPEATABLE READ';
ALTER DATABASE isolation_exp SET DEFAULT_TRANSACTION_ISOLATION TO 'READ COMMITED';