SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL read committed;
-- SHOW default_transaction_isolation;
